### ISSUE TITLE
Mettre un logo dans le header

### ISSUE THREAD

**Issue by T4GAD4** [mcaboche/ContinuousDeployment#3]
**En tant que** PO,
**Je souhaite** afficher le logo Sogeti dans le header
**Afin que** tout le monde sache que l'application est Sogeti.

Critères d'acceptance :
Lien vers le logo : `/assets/logo.png`
Hauteur maximale du logo : 60px

**Comment by PerthuisQuentin** [comment]
ça marche chez moi. ¯\_(ツ)_/¯
![image](https://user-images.githubusercontent.com/16955502/68790747-2e27e580-0648-11ea-9a5d-c74c417741b0.png)
